name: p4dev
channels:
  - conda-forge
  - psi4/label/dev
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - sphinx
  - nbsphinx
  - psi4
  - jupyter
  - matplotlib

